const {test,expect}=require('@playwright/test');
const ROUTE='/news/2026-10-06/anthropic-subscriptions-offer-5x-more-value-than-openai/';
test('artwork precedes prose; separate image threads load on request and do not move desktop prose',async({page})=>{
 const requests=[],posts=[];
 await page.route('**/v/desk-comments?*',async r=>{const slug=new URL(r.request().url()).searchParams.get('slug');requests.push(slug);await r.fulfill({json:{ok:true,slug,count:0,comments:[]}})});
 await page.route('**/v/desk-comments',async r=>{posts.push(r.request().postDataJSON());await r.fulfill({status:202,json:{ok:true,status:'held',message:'Your comment is waiting for review.'}})});
 await page.setViewportSize({width:1366,height:900});
 await page.goto(ROUTE);
 const stage=page.locator('.desk-art-stage').first(),story=page.locator('#story');
 expect((await stage.boundingBox()).y).toBeLessThan((await story.boundingBox()).y);
 const image=page.locator('[data-comment-target="editorial-illustration-1"]'),cartoon=page.locator('[data-comment-target="satire-cartoon"]');
 const imageSlug=await image.getAttribute('data-slug'),cartoonSlug=await cartoon.getAttribute('data-slug');
 expect(imageSlug).toMatch(/^2026-10-06\/art-[a-f0-9]{32}$/);expect(cartoonSlug).not.toBe(imageSlug);
 expect(await page.locator('#community').getAttribute('data-slug')).not.toBe(imageSlug);
 expect(requests).not.toContain(imageSlug);
 const proseY=()=>page.locator('.desk-tldr').evaluate(e=>e.getBoundingClientRect().top+scrollY);
 const before=await proseY();
 await page.getByText('Comment on the illustration',{exact:true}).click();
 await expect(image.locator('textarea')).toBeVisible();expect(requests).toContain(imageSlug);expect(requests).not.toContain(cartoonSlug);
 expect(Math.abs(await proseY()-before)).toBeLessThan(20);
 await page.evaluate(()=>{window.VSCsrf={getToken:()=>Promise.resolve('test.csrf')};window.VSTurnstile={getToken:()=>Promise.resolve('test.turnstile')};});
 await image.locator('textarea').fill('The illustration captures the contrast well.');
 await image.getByLabel('Display name',{exact:true}).fill('Reader');
 await image.getByRole('button',{name:'Post comment',exact:true}).click();
 await expect(image.getByRole('status').filter({hasText:'waiting for review'})).toBeVisible();
 expect(posts[0].slug).toBe(imageSlug);
 await page.getByText('Comment on the cartoon',{exact:true}).click();await expect(cartoon.locator('textarea')).toBeVisible();expect(requests).toContain(cartoonSlug);
 const community=page.locator('#community');await community.scrollIntoViewIfNeeded();
 await community.locator('textarea').fill('The sources help distinguish the claim from the commentary.');
 await community.getByLabel('Display name',{exact:true}).fill('Reader');
 await page.evaluate(()=>{window.VSTurnstile.getToken=slot=>{window.challengeThread=slot.closest('[data-desk-comments]').getAttribute('data-slug');return Promise.resolve('test.turnstile')}});
 await community.getByRole('button',{name:'Post comment',exact:true}).click();
 await expect(community.getByRole('status').filter({hasText:'waiting for review'})).toBeVisible();
 expect(await page.evaluate(()=>window.challengeThread)).toBe(await community.getAttribute('data-slug'));
 await expect(cartoon.locator('textarea')).toBeHidden();
});
test('mobile artwork fits; sourced brief and commentary precede satire and disclosure',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto(ROUTE);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 const cartoon=page.locator('#satire-cartoon');await expect(cartoon).toBeVisible();
 const position=selector=>page.locator(selector).evaluate(e=>e.getBoundingClientRect().top+scrollY);
 expect(await position('#positions')).toBeLessThan(await position('#satire-cartoon'));
 expect(await position('#satire-cartoon')).toBeLessThan(await position('#how-this-was-written'));
 await expect(page.getByRole('heading',{name:'News Brief',exact:true})).toBeVisible();
 expect(await page.locator('.desk-news-brief li').count()).toBe(await page.locator('.desk-facts>li').count());
 await expect(page.getByRole('heading',{name:'The Desk’s Take',exact:true})).toBeVisible();
 await expect(page.locator('.desk-art-feedback').first()).toBeVisible();
});
