#!/usr/bin/env node
// S147 gtag-defer-and-consent: replace the eager inline gtag bootstrap with
// an idle-callback deferred init. Same DOM, same analytics ID — just no
// longer competes with critical-path rendering.
//
// Pattern targeted (must match identically — generated by propagate-nav):
//   <!-- Google tag (gtag.js) -->
//   <script async src="https://www.googletagmanager.com/gtag/js?id=G-RSGLPP4KDZ"></script>
//   <script>
//     window.dataLayer = window.dataLayer || [];
//     function gtag(){dataLayer.push(arguments);}
//     gtag('js', new Date());
//     gtag('config', 'G-RSGLPP4KDZ');
//   </script>
//
// Replacement:
//   <!-- Google tag (gtag.js) — S147 deferred to idle -->
//   <script>
//     (function(){
//       function boot(){
//         var s=document.createElement('script');
//         s.async=true;
//         s.src='https://www.googletagmanager.com/gtag/js?id=G-RSGLPP4KDZ';
//         document.head.appendChild(s);
//         window.dataLayer=window.dataLayer||[];
//         function gtag(){dataLayer.push(arguments);}
//         window.gtag=gtag;
//         gtag('js',new Date());
//         gtag('config','G-RSGLPP4KDZ');
//       }
//       if('requestIdleCallback' in window){requestIdleCallback(boot,{timeout:2000});}
//       else{setTimeout(boot,1500);}
//     })();
//   </script>

import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const FIND = `<!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-RSGLPP4KDZ"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-RSGLPP4KDZ');
  </script>`;

const REPLACE = `<!-- Google tag (gtag.js) — S147 deferred to idle -->
  <script>(function(){function boot(){var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=G-RSGLPP4KDZ';document.head.appendChild(s);window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}window.gtag=gtag;gtag('js',new Date());gtag('config','G-RSGLPP4KDZ');}if('requestIdleCallback' in window){requestIdleCallback(boot,{timeout:2000});}else{setTimeout(boot,1500);}})();</script>`;

const VARIANT = /<!-- Google tag \(gtag\.js\) -->\s*<script\s+async\s+src="https:\/\/www\.googletagmanager\.com\/gtag\/js\?id=G-RSGLPP4KDZ"><\/script>\s*<script>\s*window\.dataLayer\s*=\s*window\.dataLayer\s*\|\|\s*\[\];\s*function\s+gtag\(\)\s*\{\s*dataLayer\.push\(arguments\);\s*\}\s*gtag\('js',\s*new Date\(\)\);\s*gtag\('config',\s*'G-RSGLPP4KDZ'\);\s*<\/script>/m;
const BARE_VARIANT = /<script\s+async\s+src="https:\/\/www\.googletagmanager\.com\/gtag\/js\?id=G-RSGLPP4KDZ"><\/script>\s*<script>\s*window\.dataLayer\s*=\s*window\.dataLayer\s*\|\|\s*\[\];\s*function\s+gtag\(\)\s*\{\s*dataLayer\.push\(arguments\);\s*\}\s*gtag\('js',\s*new Date\(\)\);\s*gtag\('config',\s*'G-RSGLPP4KDZ'\);\s*<\/script>/m;

const files = execSync('git ls-files "*index.html" "*.html"', { encoding: 'utf8' })
  .split('\n')
  .filter(Boolean)
  .filter(f => !f.startsWith('node_modules/'));

let changed = 0;
let skipped = 0;
let notFound = 0;
for (const file of files) {
  let html;
  try { html = readFileSync(file, 'utf8'); } catch { continue; }
  if (!html.includes('googletagmanager.com/gtag/js?id=G-RSGLPP4KDZ')) { skipped++; continue; }
  if (html.includes('S147 deferred to idle')) { skipped++; continue; }
  let next = html.includes(FIND) ? html.replace(FIND, REPLACE) : html.replace(VARIANT, REPLACE);
  if (next === html) next = html.replace(BARE_VARIANT, REPLACE);
  if (next === html) { notFound++; console.warn('  ! pattern not found in', file); continue; }
  writeFileSync(file, next);
  changed++;
}
console.log(`✓ defer-gtag: ${changed} files updated, ${skipped} skipped, ${notFound} pattern-miss`);
