#!/usr/bin/env node
/**
 * inject-lqip.mjs — inline LQIP backgrounds into <img data-lqip> tags.
 *
 * Reads `data/lqip-map.json` (generated by `build-lqip-map.mjs`), walks
 * every HTML file, and for each `<img ... data-lqip ... src="X">` rewrites
 * the tag to include `style="background-image:url(<base64>);background-size:cover"`.
 * Existing `background-image:url(data:image/webp;base64,...)` chunks are
 * detected and replaced (idempotent — re-runs with the same map are no-ops).
 *
 * Why build-time, not runtime: the placeholder must paint before the real
 * image decodes. A fetch+set-style at runtime races the network.
 *
 * Usage:
 *   node scripts/inject-lqip.mjs           # apply (writes HTML files)
 *   node scripts/inject-lqip.mjs --check   # fail if any tagged img is stale
 */
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const MAP_PATH = path.join(ROOT, 'data', 'lqip-map.json');

const CHECK = process.argv.includes('--check');

function walkHtml(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walkHtml(p, out);
    else if (e.name.endsWith('.html')) out.push(p);
  }
  return out;
}

function resolveSrc(htmlFile, src) {
  if (!src) return null;
  if (/^https?:/i.test(src)) return null;
  if (src.startsWith('//')) return null;
  const isAbs = src.startsWith('/');
  const base = isAbs ? ROOT : path.dirname(htmlFile);
  const rel  = isAbs ? src.slice(1) : src;
  return path.relative(ROOT, path.resolve(base, rel)).replace(/\\/g, '/');
}

// Match a single <img ...> tag that has data-lqip somewhere among its attributes.
// Capture group 1 = entire opening tag minus the closing `>`.
const IMG_RE = /<img\b([^>]*\bdata-lqip\b[^>]*?)\/?>/gi;
const SRC_RE = /\bsrc=["']([^"']+)["']/i;
const STYLE_RE = /\bstyle=["']([^"']*)["']/i;

function applyStyleToInner(inner, dataUrl) {
  // Build the LQIP fragment we want present.
  const bg = `background-image:url(${dataUrl});background-size:cover;background-repeat:no-repeat`;
  if (STYLE_RE.test(inner)) {
    return inner.replace(STYLE_RE, (_, existing) => {
      // Strip any prior LQIP background, then prepend ours.
      const stripped = existing
        .replace(/background-image\s*:\s*url\(data:image\/[^)]+\)\s*;?\s*/i, '')
        .replace(/background-size\s*:\s*cover\s*;?\s*/i, '')
        .replace(/background-repeat\s*:\s*no-repeat\s*;?\s*/i, '')
        .trim();
      const sep = stripped && !stripped.endsWith(';') ? ';' : '';
      return `style="${bg};${sep}${stripped}"`;
    });
  }
  return `${inner} style="${bg}"`;
}

function processHtml(file, map) {
  const original = fs.readFileSync(file, 'utf8');
  let touched = false;
  const next = original.replace(IMG_RE, (whole, inner) => {
    const srcMatch = inner.match(SRC_RE);
    if (!srcMatch) return whole;
    const resolved = resolveSrc(file, srcMatch[1]);
    if (!resolved || !map[resolved]) return whole;
    const rewritten = `<img${applyStyleToInner(inner, map[resolved])}>`;
    if (rewritten !== whole) touched = true;
    return rewritten;
  });
  return { next, touched };
}

function main() {
  let mapJson;
  try { mapJson = JSON.parse(fs.readFileSync(MAP_PATH, 'utf8')); }
  catch {
    console.log('inject-lqip: no data/lqip-map.json yet (run build-lqip-map.mjs) — skip');
    return;
  }
  const map = mapJson.map || {};
  const files = walkHtml(ROOT);
  let touchedCount = 0;
  let staleFiles = [];

  for (const f of files) {
    const { next, touched } = processHtml(f, map);
    if (!touched) continue;
    if (CHECK) staleFiles.push(path.relative(ROOT, f).replace(/\\/g, '/'));
    else {
      fs.writeFileSync(f, next);
      touchedCount++;
    }
  }

  if (CHECK) {
    if (staleFiles.length) {
      console.error(`inject-lqip --check: ${staleFiles.length} HTML file(s) need LQIP inlining:`);
      for (const s of staleFiles.slice(0, 10)) console.error(`  - ${s}`);
      console.error('  Run: node scripts/inject-lqip.mjs');
      process.exit(1);
    }
    console.log('inject-lqip --check: all tagged <img> tags up to date');
    return;
  }
  console.log(`inject-lqip: updated ${touchedCount} HTML file(s)`);
}

main();
