#!/usr/bin/env node
/**
 * resync-derived.mjs  (S309)
 *
 * Repairs the derived-artifact graph after a rebase/merge, using the SAME
 * evidence graph that check-publish-cascade-coverage validates against.
 *
 * The gap this closes: the repo could DETECT cascade drift but had no way to
 * REPAIR it short of a ~11-minute full `npm run build`. Observed live (S309):
 * a rebase whose 32 conflicts were all generated files was resolved with
 * `git checkout --theirs`, and the two feeds named in the conflict list were
 * regenerated by hand. Push was then rejected three times in a row — first
 * candidate-artifact-manifest, then release-proof — because those artifacts had
 * never CONFLICTED. They merely hash inputs that moved underneath them.
 *
 * That is the whole lesson, and it is why this tool reads the graph instead of
 * the conflict list:
 *
 *   a conflict list shows COLLISIONS; it does not show DEPENDENTS.
 *
 * Fixing dependents one at a time cannot converge either, because a node's
 * source can be another node's output — so repairing one dirties the next. The
 * fix has to be closure + topological order, which is exactly what the graph
 * already encodes.
 *
 * Usage:
 *   node scripts/resync-derived.mjs --since <ref>   # default: ORIG_HEAD (set by rebase/merge)
 *   node scripts/resync-derived.mjs --changed a,b   # explicit file list (CI / testing)
 *   node scripts/resync-derived.mjs --dry-run       # print the plan, build nothing
 *   node scripts/resync-derived.mjs --verify        # after building, run each node's own --check
 *
 * Exit 0 = tree consistent. Non-zero = a builder or a --check failed; the
 * message names the node so the next step is never a guess.
 */

import { execFileSync } from './lib/safe-spawn.mjs';
import { existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEvidenceGraph, validateEvidenceGraph, affectedEvidenceNodes } from './lib/evidence-graph.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const arg = (name, fallback = null) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  if (hit) return hit.slice(name.length + 3);
  const idx = process.argv.indexOf(`--${name}`);
  return idx !== -1 && process.argv[idx + 1] && !process.argv[idx + 1].startsWith('--')
    ? process.argv[idx + 1]
    : fallback;
};

/**
 * windowsHide is mandatory on every spawn in this studio (§0 window-storm):
 * without it a shell spawn pops a visible console per call on Windows, and this
 * tool spawns once per dirty node.
 */
const git = (args) =>
  execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', windowsHide: true }).trim();

export function changedFilesSince(ref) {
  // Three dots would diff against the merge-base, which after a rebase is not
  // the pre-rebase tree and would under-report what actually moved.
  return git(['diff', '--name-only', `${ref}..HEAD`]).split('\n').map((s) => s.trim()).filter(Boolean);
}

/**
 * Topologically order nodes so a node is always rebuilt AFTER any node whose
 * output it consumes. Without this the tool would produce exactly the
 * whack-a-mole it exists to prevent — building a dependent against a source
 * that is itself about to be rewritten.
 *
 * The graph is validated acyclic by validateEvidenceGraph, so a plain DFS is
 * safe; the `visiting` set is kept as a defensive stop rather than a cycle
 * detector, since a cycle is already a hard error upstream.
 */
export function topoOrder(nodes, graph) {
  const byOutput = new Map(graph.nodes.map((n) => [n.output, n]));
  const selected = new Map(nodes.map((n) => [n.id, n]));
  const ordered = [];
  const done = new Set();
  const visiting = new Set();
  const visit = (node) => {
    if (done.has(node.id) || visiting.has(node.id)) return;
    visiting.add(node.id);
    for (const source of node.sources) {
      const upstream = byOutput.get(source);
      if (upstream && selected.has(upstream.id)) visit(upstream);
    }
    visiting.delete(node.id);
    done.add(node.id);
    ordered.push(node);
  };
  for (const node of nodes) visit(node);
  return ordered;
}

/** Output + any sibling paths the builder writes alongside it (append-only ledgers). */
export function stagePaths(node) {
  return [node.output, ...(node.alsoStage || [])];
}

function main() {
  const graph = loadEvidenceGraph(ROOT);
  const graphErrors = validateEvidenceGraph(graph);
  if (graphErrors.length) {
    for (const e of graphErrors) console.error(`resync-derived: evidence graph invalid — ${e}`);
    process.exit(1);
  }

  const explicit = arg('changed');
  let changed;
  if (explicit) {
    changed = explicit.split(',').map((s) => s.trim()).filter(Boolean);
  } else {
    const ref = arg('since', 'ORIG_HEAD');
    try {
      git(['rev-parse', '--verify', `${ref}^{commit}`]);
    } catch {
      console.error(`resync-derived: cannot resolve --since ref "${ref}".`);
      console.error('  after a rebase/merge git sets ORIG_HEAD; otherwise pass --since <sha> explicitly.');
      process.exit(1);
    }
    changed = changedFilesSince(ref);
  }

  if (!changed.length) {
    console.log('resync-derived: no changed files — nothing to resync');
    process.exit(0);
  }

  // A node whose source git does not track can never appear in `git diff`, so
  // closure over the changed set silently skips it — forever, not just once.
  // founder-presence reads context/.session-lock, which is untracked: the lock
  // is written at session start and cleared at closeout, so its output changes
  // on exactly the boundary a rebase happens, and this tool reported success
  // while leaving it stale (S309, caught by the pre-push coherence hook).
  // Treat any node with an untracked, non-glob source as always dirty: cheap,
  // and the alternative is a repairer that is quietly wrong once per session.
  const untrackedSourced = graph.nodes.filter((n) => n.sources.some((s) => {
    if (s.includes('*')) return false;
    try {
      git(['ls-files', '--error-unmatch', '--', s]);
      return false;
    } catch {
      return true;
    }
  }));
  const seeds = [...new Set([...changed, ...untrackedSourced.map((n) => n.output)])];
  const dirty = topoOrder(affectedEvidenceNodes(graph, seeds), graph);
  if (untrackedSourced.length) {
    for (const n of untrackedSourced) console.log(`  ~ ${n.id} — always rebuilt (untracked source, invisible to git diff)`);
  }
  if (!dirty.length) {
    console.log(`resync-derived: ${changed.length} changed file(s), 0 derived artifact(s) affected`);
    process.exit(0);
  }

  console.log(`resync-derived: ${changed.length} changed file(s) → ${dirty.length}/${graph.nodes.length} derived artifact(s) to rebuild`);
  for (const node of dirty) console.log(`  · ${node.id} → ${node.output}`);
  if (process.argv.includes('--dry-run')) process.exit(0);

  // A repair tool must never take a real-world action to make a file look right.
  // staging-deploy-receipt declares scripts/deploy-staging.mjs as its builder,
  // and the first run of this tool duly invoked it — attempting an actual
  // staging deploy to repair a rebase. It was stopped only by an unrelated
  // readiness check that happened to be failing (S309). The node's output is a
  // RECEIPT of a deploy, so it is not regenerable by definition: skip it, say so,
  // and leave the deploy to a human decision.
  const runnable = dirty.filter((n) => !n.sideEffecting);
  const skipped = dirty.filter((n) => n.sideEffecting);
  for (const node of skipped) {
    console.warn(`  ⊘ ${node.id} — SKIPPED, side-effecting builder (${node.builder})`);
    console.warn(`    ${node.sideEffectingReason || 'declared side-effecting in the evidence graph'}`);
  }

  for (const node of runnable) {
    const builder = join(ROOT, node.builder);
    if (!existsSync(builder)) {
      console.error(`resync-derived: ${node.id} declares a builder that does not exist — ${node.builder}`);
      process.exit(1);
    }
    try {
      execFileSync('node', [builder], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
    } catch (err) {
      console.error(`resync-derived: builder FAILED for ${node.id} (${node.builder})`);
      console.error(String(err.stderr || err.stdout || err.message).slice(0, 600));
      process.exit(1);
    }
    const paths = stagePaths(node).filter((p) => existsSync(join(ROOT, p)));
    if (paths.length) git(['add', '--', ...paths]);
    console.log(`  ✓ ${node.id}`);
  }

  if (process.argv.includes('--verify')) {
    // Only verify what we actually rebuilt; a skipped node's check may legitimately
    // still fail, and reporting that as a repair failure would be noise.
    // A repairer that reports success without re-reading its own output is the
    // same shape of lie as a checker that never runs. Re-run each node's own
    // --check against the bytes now on disk.
    let failed = 0;
    for (const node of runnable) {
      const [cmd, ...rest] = node.check;
      try {
        execFileSync(cmd, rest, { cwd: ROOT, stdio: 'pipe', windowsHide: true });
      } catch {
        console.error(`resync-derived --verify: ${node.id} still drifted after rebuild`);
        failed += 1;
      }
    }
    if (failed) process.exit(1);
    console.log(`resync-derived --verify: ${runnable.length}/${runnable.length} rebuilt artifact(s) pass their own --check`);
  }

  console.log(`resync-derived: ${runnable.length} artifact(s) rebuilt + staged${skipped.length ? ` · ${skipped.length} skipped (side-effecting)` : ''}`);
  process.exit(0);
}

function selfTest() {
  const graph = loadEvidenceGraph(ROOT);
  const cases = [];

  cases.push(['live evidence graph is valid', validateEvidenceGraph(graph).length === 0]);

  // A dependent is dirtied by its SOURCE moving, never by appearing in a
  // conflict list — the S309 defect this tool exists to prevent.
  const withUpstream = graph.nodes.find((n) =>
    n.sources.some((s) => graph.nodes.some((u) => u.output === s)));
  if (withUpstream) {
    const upstream = graph.nodes.find((u) => withUpstream.sources.includes(u.output));
    const hit = affectedEvidenceNodes(graph, [upstream.sources[0]]).map((n) => n.id);
    cases.push([`transitive: dirtying ${upstream.id}'s source also dirties ${withUpstream.id}`,
      hit.includes(upstream.id) && hit.includes(withUpstream.id)]);

    // ...and the dependent must be ordered AFTER the source it consumes.
    const order = topoOrder(affectedEvidenceNodes(graph, [upstream.sources[0]]), graph).map((n) => n.id);
    cases.push(['topological: source builds before its dependent',
      order.indexOf(upstream.id) < order.indexOf(withUpstream.id)]);
  } else {
    cases.push(['graph has at least one node-to-node edge to test', false]);
  }

  // Negative: an unrelated file must dirty nothing. A repairer that rebuilds
  // everything on every invocation is just a slow `npm run build` with a new name.
  cases.push(['unrelated file affects no node',
    affectedEvidenceNodes(graph, ['README.md']).length === 0]);

  // alsoStage siblings must be staged, or a feed lands without the ledger its
  // own inputs are rebuilt from (the strand class check-publish-cascade guards).
  const withSiblings = graph.nodes.find((n) => n.alsoStage?.length);
  cases.push(['alsoStage siblings are staged with the output',
    !withSiblings || withSiblings.alsoStage.every((p) => stagePaths(withSiblings).includes(p))]);

  // Every node this tool would run must declare a builder that actually exists,
  // otherwise the repair path is dead for that node and nobody finds out until
  // a push is already being rejected.
  // Structural guard, not an exception list: any builder that ACTS on the world
  // (deploys, publishes, promotes, sends) must be declared sideEffecting, or this
  // tool would invoke it to make a file look right after a rebase. Matched on the
  // basename PREFIX so `build-deploy-currency.mjs` — a pure generator with
  // "deploy" in its name — is not swept up.
  const undeclared = graph.nodes
    .filter((n) => /^(deploy|publish|promote|send|notify)-/.test(n.builder.split('/').pop()) && !n.sideEffecting)
    .map((n) => n.id);
  cases.push([`every world-acting builder is declared sideEffecting${undeclared.length ? ` (undeclared: ${undeclared.join(', ')})` : ''}`,
    undeclared.length === 0]);
  cases.push(['side-effecting nodes explain why, so the skip is auditable',
    graph.nodes.filter((n) => n.sideEffecting)
      .every((n) => typeof n.sideEffectingReason === 'string' && n.sideEffectingReason.length > 20)]);

  // A node reading an untracked file must be rebuilt unconditionally — git diff
  // cannot see that file change, so closure alone leaves it stale every time.
  const untracked = graph.nodes.filter((n) => n.sources.some((s) => {
    if (s.includes('*')) return false;
    try {
      execFileSync('git', ['ls-files', '--error-unmatch', '--', s], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
      return false;
    } catch { return true; }
  })).map((n) => n.id);
  cases.push([`untracked-source nodes are known and force-rebuilt${untracked.length ? ` (${untracked.join(', ')})` : ' (none)'}`,
    Array.isArray(untracked)]);
  // founder-presence is the live instance: it reads context/.session-lock, which
  // is written at session start and cleared at closeout. If it ever stops being
  // detected as untracked-sourced, this tool has gone quietly stale again.
  const fp = graph.nodes.find((n) => n.id === 'founder-presence');
  cases.push(['founder-presence is still recognised as untracked-sourced',
    !fp || untracked.includes('founder-presence')]);

  const missing = graph.nodes.filter((n) => !existsSync(join(ROOT, n.builder))).map((n) => n.id);
  cases.push([`all ${graph.nodes.length} builders exist${missing.length ? ` (missing: ${missing.join(', ')})` : ''}`,
    missing.length === 0]);

  const failed = cases.filter(([, ok]) => !ok);
  cases.forEach(([name, ok]) => console.log(`  ${ok ? 'ok' : 'FAIL'} ${name}`));
  console.log(`resync-derived --self-test: ${cases.length - failed.length}/${cases.length} passed`);
  process.exit(failed.length ? 1 : 0);
}

if (process.argv.includes('--self-test')) selfTest();
else main();
