#!/usr/bin/env node
/**
 * resync-derived.mjs  (S309)
 *
 * Repairs the derived-artifact graph after a rebase/merge, using the SAME
 * evidence graph that check-publish-cascade-coverage validates against.
 *
 * The gap this closes: the repo could DETECT cascade drift but had no way to
 * REPAIR it short of a ~11-minute full `npm run build`. Observed live (S309):
 * a rebase whose 32 conflicts were all generated files was resolved with
 * `git checkout --theirs`, and the two feeds named in the conflict list were
 * regenerated by hand. Push was then rejected three times in a row — first
 * candidate-artifact-manifest, then release-proof — because those artifacts had
 * never CONFLICTED. They merely hash inputs that moved underneath them.
 *
 * That is the whole lesson, and it is why this tool reads the graph instead of
 * the conflict list:
 *
 *   a conflict list shows COLLISIONS; it does not show DEPENDENTS.
 *
 * Fixing dependents one at a time cannot converge either, because a node's
 * source can be another node's output — so repairing one dirties the next. The
 * fix has to be closure + topological order, which is exactly what the graph
 * already encodes.
 *
 * Usage:
 *   node scripts/resync-derived.mjs --since <ref>   # default: ORIG_HEAD (set by rebase/merge)
 *   node scripts/resync-derived.mjs --changed a,b   # explicit file list (CI / testing)
 *   node scripts/resync-derived.mjs --dry-run       # print the plan, build nothing
 *   node scripts/resync-derived.mjs --verify        # after building, run each node's own --check
 *   node scripts/resync-derived.mjs --no-sweep     # skip the unmodeled sweep (faster, less honest)
 *   node scripts/resync-derived.mjs --sweep-repair # rebuild what the sweep finds drifted
 *
 * THE SECOND GAP (S345). The graph models 29 of 67 byte-checked generators, and
 * check-evidence-graph-coverage deliberately keeps that a visible RATCHET rather
 * than guessing the other 38 nodes' sources — a confidently wrong graph is worse
 * than an admittedly partial one. But the debt was only visible in a config file,
 * never at the moment of repair, which is the only moment it costs anything. This
 * tool printed `0 derived artifact(s) affected` and `N artifact(s) rebuilt` with
 * no hint that either number was scoped to the subset it can see.
 *
 * Measured live, twice. S340: four publisher rebases were each resolved through
 * this tool, which rebuilt up to 20 artifacts and reported clean — then
 * build-intelligence-budget --check failed in CI at build:check step 185 of run
 * 33702593208, because that generator is not in the graph. S341 reproduced it and
 * found a SECOND member, build-nervous-system. Both were fixed by hand, both are
 * still unmodeled today.
 *
 * So the sweep measures rather than predicts: it runs the UNMODELED generators'
 * own `--check`, which is read-only and needs no `sources` to be correct. A
 * `--check` failure is not a guess about what a rebase might have touched — it is
 * the artifact itself reporting that it no longer matches its inputs. Repair
 * stays opt-in (`--sweep-repair`) because a repairer that blindly invokes 38
 * arbitrary builders is the exact hazard the sideEffecting guard above exists to
 * prevent. Default behaviour is to FAIL, NAMED — turning a ten-minute remote CI
 * red into an immediate local one.
 *
 * Exit 0 = tree consistent. Non-zero = a builder or a --check failed; the
 * message names the node so the next step is never a guess.
 */

import { execFileSync } from './lib/safe-spawn.mjs';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEvidenceGraph, validateEvidenceGraph, affectedEvidenceNodes } from './lib/evidence-graph.mjs';
import { coverage } from './check-evidence-graph-coverage.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const arg = (name, fallback = null) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  if (hit) return hit.slice(name.length + 3);
  const idx = process.argv.indexOf(`--${name}`);
  return idx !== -1 && process.argv[idx + 1] && !process.argv[idx + 1].startsWith('--')
    ? process.argv[idx + 1]
    : fallback;
};

/**
 * windowsHide is mandatory on every spawn in this studio (§0 window-storm):
 * without it a shell spawn pops a visible console per call on Windows, and this
 * tool spawns once per dirty node.
 */
const git = (args) =>
  execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', windowsHide: true }).trim();

export function changedFilesSince(ref) {
  // Three dots would diff against the merge-base, which after a rebase is not
  // the pre-rebase tree and would under-report what actually moved.
  return git(['diff', '--name-only', `${ref}..HEAD`]).split('\n').map((s) => s.trim()).filter(Boolean);
}

/**
 * Topologically order nodes so a node is always rebuilt AFTER any node whose
 * output it consumes. Without this the tool would produce exactly the
 * whack-a-mole it exists to prevent — building a dependent against a source
 * that is itself about to be rewritten.
 *
 * The graph is validated acyclic by validateEvidenceGraph, so a plain DFS is
 * safe; the `visiting` set is kept as a defensive stop rather than a cycle
 * detector, since a cycle is already a hard error upstream.
 */
export function topoOrder(nodes, graph) {
  const byOutput = new Map(graph.nodes.map((n) => [n.output, n]));
  const selected = new Map(nodes.map((n) => [n.id, n]));
  const ordered = [];
  const done = new Set();
  const visiting = new Set();
  const visit = (node) => {
    if (done.has(node.id) || visiting.has(node.id)) return;
    visiting.add(node.id);
    for (const source of node.sources) {
      const upstream = byOutput.get(source);
      if (upstream && selected.has(upstream.id)) visit(upstream);
    }
    visiting.delete(node.id);
    done.add(node.id);
    ordered.push(node);
  };
  for (const node of nodes) visit(node);
  return ordered;
}

/** Output + any sibling paths the builder writes alongside it (append-only ledgers). */
export function stagePaths(node) {
  return [node.output, ...(node.alsoStage || [])];
}

/**
 * The set of byte-checked generators that build:check gates but the evidence
 * graph does NOT model. Read from the same two sources the ratchet reads, so the
 * two can never disagree about what is covered.
 */
export function unmodeledCheckedGenerators(root = ROOT) {
  const steps = JSON.parse(
    readFileSync(join(root, 'package.json'), 'utf8')).scripts['build:check:steps'];
  return coverage(steps, loadEvidenceGraph(root)).unmodeled;
}

/**
 * Run each unmodeled generator's own `--check`. Read-only by construction: a
 * `--check` compares bytes against inputs and writes nothing, which is what makes
 * it safe to run over generators whose sources we deliberately do not model.
 *
 * Returns the drifted set. Repair is the caller's decision, never this function's.
 */
export function sweepUnmodeled(generators, { repair = false } = {}) {
  const drifted = [];
  for (const gen of generators) {
    const builder = join(ROOT, gen);
    if (!existsSync(builder)) {
      // A gated generator that no longer exists is a build:check failure waiting
      // to happen; name it rather than silently sweeping over it.
      drifted.push({ gen, reason: 'builder missing' });
      continue;
    }
    try {
      execFileSync('node', [builder, '--check'], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
    } catch {
      drifted.push({ gen, reason: 'drifted' });
    }
  }
  if (!repair || !drifted.length) return drifted;

  const stillDrifted = [];
  for (const entry of drifted) {
    if (entry.reason === 'builder missing') { stillDrifted.push(entry); continue; }
    // Same structural guard as the graph path: a repairer must never invoke a
    // builder that ACTS on the world to make a file look right after a rebase.
    if (/^(deploy|publish|promote|send|notify)-/.test(entry.gen.split('/').pop())) {
      console.warn(`  ⊘ ${entry.gen} — SKIPPED, world-acting builder; repair it deliberately`);
      stillDrifted.push({ ...entry, reason: 'world-acting, not auto-repaired' });
      continue;
    }
    const builder = join(ROOT, entry.gen);
    try {
      execFileSync('node', [builder], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
      execFileSync('node', [builder, '--check'], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
      console.log(`  ✓ ${entry.gen} — rebuilt (sweep)`);
    } catch {
      stillDrifted.push({ ...entry, reason: 'still drifted after rebuild' });
    }
  }
  return stillDrifted;
}

/**
 * Every success path in main() routes through here. That is the whole point: the
 * S340 incident exited via `0 derived artifact(s) affected`, so a sweep wired only
 * into the rebuild path would have missed it.
 */
function finish(summary) {
  if (process.argv.includes('--no-sweep')) {
    console.log(`${summary} · sweep SKIPPED (--no-sweep) — coverage of unmodeled generators unverified`);
    process.exit(0);
  }
  const unmodeled = unmodeledCheckedGenerators();
  const repair = process.argv.includes('--sweep-repair');
  const drifted = sweepUnmodeled(unmodeled, { repair });
  if (drifted.length) {
    console.error(`${summary} · sweep found ${drifted.length}/${unmodeled.length} UNMODELED artifact(s) drifted:`);
    for (const d of drifted) console.error(`  ✗ ${d.gen} — ${d.reason}`);
    console.error('  these are gated by build:check but absent from the evidence graph, so the');
    console.error('  graph walk above could not see them. Re-run with --sweep-repair, or rebuild');
    console.error('  each by hand, then model it in config/evidence-graph.json.');
    process.exit(1);
  }
  console.log(`${summary} · sweep: ${unmodeled.length} unmodeled generator(s) checked, all in sync`);
  process.exit(0);
}

function main() {
  const graph = loadEvidenceGraph(ROOT);
  const graphErrors = validateEvidenceGraph(graph);
  if (graphErrors.length) {
    for (const e of graphErrors) console.error(`resync-derived: evidence graph invalid — ${e}`);
    process.exit(1);
  }

  const explicit = arg('changed');
  let changed;
  if (explicit) {
    changed = explicit.split(',').map((s) => s.trim()).filter(Boolean);
  } else {
    const ref = arg('since', 'ORIG_HEAD');
    try {
      git(['rev-parse', '--verify', `${ref}^{commit}`]);
    } catch {
      console.error(`resync-derived: cannot resolve --since ref "${ref}".`);
      console.error('  after a rebase/merge git sets ORIG_HEAD; otherwise pass --since <sha> explicitly.');
      process.exit(1);
    }
    changed = changedFilesSince(ref);
  }

  if (!changed.length) {
    finish('resync-derived: no changed files — nothing to resync');
  }

  // A node whose source git does not track can never appear in `git diff`, so
  // closure over the changed set silently skips it — forever, not just once.
  // founder-presence reads context/.session-lock, which is untracked: the lock
  // is written at session start and cleared at closeout, so its output changes
  // on exactly the boundary a rebase happens, and this tool reported success
  // while leaving it stale (S309, caught by the pre-push coherence hook).
  // Treat any node with an untracked, non-glob source as always dirty: cheap,
  // and the alternative is a repairer that is quietly wrong once per session.
  const untrackedSourced = graph.nodes.filter((n) => n.sources.some((s) => {
    if (s.includes('*')) return false;
    try {
      git(['ls-files', '--error-unmatch', '--', s]);
      return false;
    } catch {
      return true;
    }
  }));
  const seeds = [...new Set([...changed, ...untrackedSourced.map((n) => n.output)])];
  const dirty = topoOrder(affectedEvidenceNodes(graph, seeds), graph);
  if (untrackedSourced.length) {
    for (const n of untrackedSourced) console.log(`  ~ ${n.id} — always rebuilt (untracked source, invisible to git diff)`);
  }
  if (!dirty.length) {
    // The S340 exit. `0 affected` is true of the graph and says nothing about the
    // 38 generators outside it, so this path sweeps like every other.
    finish(`resync-derived: ${changed.length} changed file(s), 0 derived artifact(s) affected`);
  }

  console.log(`resync-derived: ${changed.length} changed file(s) → ${dirty.length}/${graph.nodes.length} derived artifact(s) to rebuild`);
  for (const node of dirty) console.log(`  · ${node.id} → ${node.output}`);
  if (process.argv.includes('--dry-run')) {
    // A plan that lists only what the graph models is the same half-truth the
    // sweep exists to end — state the blind spot instead of implying there is none.
    const blind = process.argv.includes('--no-sweep') ? [] : unmodeledCheckedGenerators();
    console.log(`  (plan only · ${blind.length} unmodeled byte-checked generator(s) are NOT in this plan; a real run sweeps them)`);
    process.exitCode = 0;
    return;
  }

  // A repair tool must never take a real-world action to make a file look right.
  // staging-deploy-receipt declares scripts/deploy-staging.mjs as its builder,
  // and the first run of this tool duly invoked it — attempting an actual
  // staging deploy to repair a rebase. It was stopped only by an unrelated
  // readiness check that happened to be failing (S309). The node's output is a
  // RECEIPT of a deploy, so it is not regenerable by definition: skip it, say so,
  // and leave the deploy to a human decision.
  const runnable = dirty.filter((n) => !n.sideEffecting);
  const skipped = dirty.filter((n) => n.sideEffecting);
  for (const node of skipped) {
    console.warn(`  ⊘ ${node.id} — SKIPPED, side-effecting builder (${node.builder})`);
    console.warn(`    ${node.sideEffectingReason || 'declared side-effecting in the evidence graph'}`);
  }

  for (const node of runnable) {
    const builder = join(ROOT, node.builder);
    if (!existsSync(builder)) {
      console.error(`resync-derived: ${node.id} declares a builder that does not exist — ${node.builder}`);
      process.exit(1);
    }
    try {
      execFileSync('node', [builder], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
    } catch (err) {
      console.error(`resync-derived: builder FAILED for ${node.id} (${node.builder})`);
      console.error(String(err.stderr || err.stdout || err.message).slice(0, 600));
      process.exit(1);
    }
    const paths = stagePaths(node).filter((p) => existsSync(join(ROOT, p)));
    if (paths.length) git(['add', '--', ...paths]);
    console.log(`  ✓ ${node.id}`);
  }

  if (process.argv.includes('--verify')) {
    // Only verify what we actually rebuilt; a skipped node's check may legitimately
    // still fail, and reporting that as a repair failure would be noise.
    // A repairer that reports success without re-reading its own output is the
    // same shape of lie as a checker that never runs. Re-run each node's own
    // --check against the bytes now on disk.
    let failed = 0;
    for (const node of runnable) {
      const [cmd, ...rest] = node.check;
      try {
        execFileSync(cmd, rest, { cwd: ROOT, stdio: 'pipe', windowsHide: true });
      } catch {
        console.error(`resync-derived --verify: ${node.id} still drifted after rebuild`);
        failed += 1;
      }
    }
    if (failed) process.exit(1);
    console.log(`resync-derived --verify: ${runnable.length}/${runnable.length} rebuilt artifact(s) pass their own --check`);
  }

  finish(`resync-derived: ${runnable.length} artifact(s) rebuilt + staged${skipped.length ? ` · ${skipped.length} skipped (side-effecting)` : ''}`);
}

function selfTest() {
  const graph = loadEvidenceGraph(ROOT);
  const cases = [];

  cases.push(['live evidence graph is valid', validateEvidenceGraph(graph).length === 0]);

  // A dependent is dirtied by its SOURCE moving, never by appearing in a
  // conflict list — the S309 defect this tool exists to prevent.
  const withUpstream = graph.nodes.find((n) =>
    n.sources.some((s) => graph.nodes.some((u) => u.output === s)));
  if (withUpstream) {
    const upstream = graph.nodes.find((u) => withUpstream.sources.includes(u.output));
    const hit = affectedEvidenceNodes(graph, [upstream.sources[0]]).map((n) => n.id);
    cases.push([`transitive: dirtying ${upstream.id}'s source also dirties ${withUpstream.id}`,
      hit.includes(upstream.id) && hit.includes(withUpstream.id)]);

    // ...and the dependent must be ordered AFTER the source it consumes.
    const order = topoOrder(affectedEvidenceNodes(graph, [upstream.sources[0]]), graph).map((n) => n.id);
    cases.push(['topological: source builds before its dependent',
      order.indexOf(upstream.id) < order.indexOf(withUpstream.id)]);
  } else {
    cases.push(['graph has at least one node-to-node edge to test', false]);
  }

  // Negative: an unrelated file must dirty nothing. A repairer that rebuilds
  // everything on every invocation is just a slow `npm run build` with a new name.
  cases.push(['unrelated file affects no node',
    affectedEvidenceNodes(graph, ['README.md']).length === 0]);

  // alsoStage siblings must be staged, or a feed lands without the ledger its
  // own inputs are rebuilt from (the strand class check-publish-cascade guards).
  const withSiblings = graph.nodes.find((n) => n.alsoStage?.length);
  cases.push(['alsoStage siblings are staged with the output',
    !withSiblings || withSiblings.alsoStage.every((p) => stagePaths(withSiblings).includes(p))]);

  // Every node this tool would run must declare a builder that actually exists,
  // otherwise the repair path is dead for that node and nobody finds out until
  // a push is already being rejected.
  // Structural guard, not an exception list: any builder that ACTS on the world
  // (deploys, publishes, promotes, sends) must be declared sideEffecting, or this
  // tool would invoke it to make a file look right after a rebase. Matched on the
  // basename PREFIX so `build-deploy-currency.mjs` — a pure generator with
  // "deploy" in its name — is not swept up.
  const undeclared = graph.nodes
    .filter((n) => /^(deploy|publish|promote|send|notify)-/.test(n.builder.split('/').pop()) && !n.sideEffecting)
    .map((n) => n.id);
  cases.push([`every world-acting builder is declared sideEffecting${undeclared.length ? ` (undeclared: ${undeclared.join(', ')})` : ''}`,
    undeclared.length === 0]);
  cases.push(['side-effecting nodes explain why, so the skip is auditable',
    graph.nodes.filter((n) => n.sideEffecting)
      .every((n) => typeof n.sideEffectingReason === 'string' && n.sideEffectingReason.length > 20)]);

  // A node reading an untracked file must be rebuilt unconditionally — git diff
  // cannot see that file change, so closure alone leaves it stale every time.
  const untracked = graph.nodes.filter((n) => n.sources.some((s) => {
    if (s.includes('*')) return false;
    try {
      execFileSync('git', ['ls-files', '--error-unmatch', '--', s], { cwd: ROOT, stdio: 'pipe', windowsHide: true });
      return false;
    } catch { return true; }
  })).map((n) => n.id);
  cases.push([`untracked-source nodes are known and force-rebuilt${untracked.length ? ` (${untracked.join(', ')})` : ' (none)'}`,
    Array.isArray(untracked)]);
  // founder-presence is the live instance: it reads context/.session-lock, which
  // is written at session start and cleared at closeout. If it ever stops being
  // detected as untracked-sourced, this tool has gone quietly stale again.
  const fp = graph.nodes.find((n) => n.id === 'founder-presence');
  cases.push(['founder-presence is still recognised as untracked-sourced',
    !fp || untracked.includes('founder-presence')]);

  const missing = graph.nodes.filter((n) => !existsSync(join(ROOT, n.builder))).map((n) => n.id);
  cases.push([`all ${graph.nodes.length} builders exist${missing.length ? ` (missing: ${missing.join(', ')})` : ''}`,
    missing.length === 0]);

  // ---- S345: the sweep, and the blindness it exists to cover ----

  const unmodeled = unmodeledCheckedGenerators();

  // The gap must be real. If this ever hits zero the graph covers everything and
  // the sweep is dead weight — but that is a change to celebrate, not to assume.
  cases.push([`byte-checked generators outside the graph are enumerable (${unmodeled.length})`,
    Array.isArray(unmodeled)]);

  // NEGATIVE CONTROL — the whole point of this session's fix. The live S340/S341
  // drifters must be invisible to the graph walk, or the sweep is testing nothing.
  // If either becomes modeled, this flips to a pass for the right reason and the
  // assertion below (drift-detectable) still covers it.
  for (const drifter of ['scripts/build-intelligence-budget.mjs', 'scripts/build-nervous-system.mjs']) {
    const node = graph.nodes.find((n) => n.builder === drifter);
    const blind = !node;
    cases.push([`graph walk cannot see ${drifter.split('/').pop()} (${blind ? 'unmodeled — sweep covers it' : 'now modeled — graph covers it'})`,
      blind ? unmodeled.includes(drifter) : true]);
  }

  // A sweep that cannot fail is a sweep that proves nothing: point it at a
  // generator that does not exist and it must report drift rather than silence.
  const bogus = sweepUnmodeled(['scripts/build-this-generator-does-not-exist.mjs']);
  cases.push(['sweep reports a missing builder rather than passing over it',
    bogus.length === 1 && bogus[0].reason === 'builder missing']);

  // An empty sweep set must not be reported as a failure.
  cases.push(['sweep over an empty set is clean', sweepUnmodeled([]).length === 0]);

  // STRUCTURAL: every success exit in main() must route through finish(), or a
  // future exit path silently reintroduces the S340 blindness. Counted from the
  // source rather than an exit-path list, so a NEW path is caught too.
  const src = readFileSync(fileURLToPath(import.meta.url), 'utf8');
  const mainBody = src.slice(src.indexOf('function main() {'), src.indexOf('function selfTest() {'));
  cases.push(['no success exit in main() bypasses the sweep (no bare process.exit(0))',
    !/process\.exit\(0\)/.test(mainBody)]);

  const failed = cases.filter(([, ok]) => !ok);
  cases.forEach(([name, ok]) => console.log(`  ${ok ? 'ok' : 'FAIL'} ${name}`));
  console.log(`resync-derived --self-test: ${cases.length - failed.length}/${cases.length} passed`);
  process.exit(failed.length ? 1 : 0);
}

if (process.argv.includes('--self-test')) selfTest();
else main();
