#!/usr/bin/env node
/**
 * lib/skill-profile.mjs — thin delegation shim (S172 protocol-script-self-heal)
 *
 * medium-overlay resolver — /start, /audit, /implement all call it first (S125+S126).
 * Canonical implementation lives in vaultspark-studio-ops; this shim forwards
 * argv verbatim with this repo as cwd. Exits 0 quietly when the sibling is
 * unreachable so the session protocol never blocks on a missing checkout.
 *
 * Generated by: node scripts/check-protocol-scripts.mjs --heal
 */
import { existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const SIBLING = path.resolve(ROOT, '..', 'vaultspark-studio-ops', 'scripts', ...'lib/skill-profile.mjs'.split('/'));

if (!existsSync(SIBLING)) {
  console.log('lib/skill-profile.mjs (shim): studio-ops sibling not reachable — skipping.');
  process.exit(0);
}
const r = spawnSync(process.execPath, [SIBLING, ...process.argv.slice(2)], { stdio: 'inherit', cwd: ROOT });
process.exit(r.status ?? 0);
